# Generated by Django 2.1.15 on 2020-05-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myip',
            options={'ordering': ['id'], 'verbose_name': 'IP', 'verbose_name_plural': 'IP'},
        ),
        migrations.AddField(
            model_name='myip',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
    ]
