# Generated by Django 2.1.15 on 2020-05-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200530_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myip',
            name='description',
            field=models.CharField(default='Без описания', max_length=255, verbose_name='Description'),
        ),
    ]
